---
title: "Relatório"
author: "Kevin, Hugo, Hideki"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#  Primeira etapa - Encontrando os mínimos locais
<p> Considere a função: </p>
<p> $S(m,b) = \sum_{j=1}^{n}(mx_j - y_j + b)^2$ </p>
<p>do método dos mínimos quadrados. </p>

##  (a) Encontre o gradiente de *S* num ponto *(m,b)* genérico.

##  (b) Mostre que o único ponto crítico *(m,b)* de *S(m,b)* é tal que
<p>$$m\sum_{j=1}^{n}x_j^2 + b\sum_{j=1}^{n}= \sum_{j=1}^{n}x_jy_j$$</p>
<p>$$m\sum_{j=1}^{n}x_j + nb= \sum_{j=1}^{n}y_j$$</p>

## (c) Mostre que a matriz Hessiana de S no ponto (m,b) é dada por:
<p>$$H(m,b)= \left[\begin{array}{cc}
2\sum_{j=1}^{n}x_j^2 & 2\sum_{j=1}^{n}x_j\\
2\sum_{j=1}^{n}x_j & 2n\\
\end{array}
\right]_{2\times 2}$$</p>
##  (d) Assuma que $$2\sum_{j=1}^{n}x_j^2 - (2\sum_{j=1}^{n}x_j)^2 > 0$$ Conclua do item (c), usando o teste da segunda derivada, que o ponto (m,b) é ponto de mínimo local

#  Segunda etapa - Determinação e esboço da reta teórica de aproximação
<p>A partir dos dados disponibilizados para a sua atividade, determine a reta teórica (escala
logaritmica) de aproximação utilizando o método dos mínimos quadrados. Faça um
esboço da reta obtida juntamente com os dados fornecidos transformados em logaritmo.</p>


# Terceira etapa - Determinação e esboço da curva exponencial
Utilize a reta do item 2 para determinar a curva exponencial associada a ela. Façaa um
esboço da exponencial juntamente com os dados fornecidos (número de casos).

# Quarta etapa - Comparação do esboço anterior com o gráfico da planilha de dados

\begin{itemize}
\item De maneira geral, que conjunto de dados melhor se aproxima da curva teórica?
\item Até que ponto (dia aproximado) as duas curvas se aproximam da curva teórica?
\end{itemize}
