---
title: "Cálculos do relatório"
author: "Kevin Zavala Mattos"
date: "14/05/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Parte 1

## (a) Gradiente de *S* num ponto *(m,b)* genérico.

<p> $S(m,b) = \sum_{j=1}^{n}(mx_j - y_j + b)^2$</p>
<p> $\nabla S(m,b) = (S_m(m_o,y_0),S_b(m_o,b_o))$</p>

<p> $S_m = \dfrac{\partial S}{\partial m} = \dfrac{\partial }{\partial m}\sum_{j=1}^{n}(mx_j - y_j + b)^2$ </p>
<p> $\dfrac{\partial S}{\partial m} = \sum_{j=1}^{n} 2(mx_j-y_j+b) (xj)$</p>
<p> $\dfrac{\partial S}{\partial m} = 2 [m\sum_{j=1}^{n}x_j^2 - \sum_{j=1}^{n}x_jy_j+b\sum_{j=1}^{n}x_j]$</p>


<p> $S_b= \dfrac{\partial S}{\partial b} = \dfrac{\partial }{\partial b}\sum_{j=1}^{n}(mx_j - y_j + b)^2$</p>
<p>$\dfrac{\partial S}{\partial b} = 2\sum_{j=1}^{n} (mx_j-y_j+b)$ </p>
<p> $\dfrac{\partial S}{\partial b} = 2[m\sum_{j=1}^{n}x_j - \sum_{j=1}^{n}y_j + \sum_{j=1}^{n}b]$</p>

##  (b) Mostre que o único ponto crítico *(m,b)* de *S(m,b)* é tal que
$$m\sum_{j=1}^{n}x_j^2 + b\sum_{j=1}^{n}x_j= \sum_{j=1}^{n}x_jy_j$$</p>
<p>$$m\sum_{j=1}^{n}x_j + nb= \sum_{j=1}^{n}y_j$$</p>

<p> **Prova:** </p>

<p> Pontos críticos = $S_m = 0$, $S_b=0$</p>
<p> $S_m = 2 [m\sum_{j=1}^{n}x_j^2 - \sum_{j=1}^{n}x_jy_j+b\sum_{j=1}^{n}x_j] = 0$</p>
<p> $$m\sum_{j=1}^{n}x_j^2 +b\sum_{j=1}^{n}x_j = \sum_{j=1}^{n}x_jy_j$$</p>

<p> $S_b=  2[m\sum_{j=1}^{n}x_j - \sum_{j=1}^{n}y_j + \sum_{j=1}^{n}b] = 0$</p>
<p> **Obs:$\sum_{j=1}^{n}b = nb$**<p>
<p> $$m\sum_{j=1}^{n}x_j + nb = \sum_{j=1}^{n}y_j$$</p>

## (c) Mostre que a matriz Hessiana de S no ponto (m,b) é dada por:
<p>$$H(m,b)= \left[\begin{array}{cc}
2\sum_{j=1}^{n}x_j^2 & 2\sum_{j=1}^{n}x_j\\
2\sum_{j=1}^{n}x_j & 2n\\
\end{array}
\right]_{2\times 2}$$</p>

<p> **Prova:** </p>

$$H(m,b)= \left[\begin{array}{cc}
S_{mm}(m,b) & S_{mb}(m,b)\\
S_{mb}(m,b)& S_{mm}(m,b)\\
\end{array}
\right]_{2\times 2}$$

<p> $S_{mm} = \dfrac{\partial^2 S}{\partial^2 m} 2 [m\sum_{j=1}^{n}x_j^2 - \sum_{j=1}^{n}x_jy_j+b\sum_{j=1}^{n}x_j]$</p>
<p> $\dfrac{\partial^2 S}{\partial^2 m} m\sum_{j=1}^{n}x_j^2 = \sum_{j=1}^{n}x_j^2$ </p>
<p> $\dfrac{\partial^2 S}{\partial^2 m}- \sum_{j=1}^{n}x_jy_j=0$ & $\dfrac{\partial^2 f}{\partial^2 m}b\sum_{j=1}^{n}x_j=0$</p>
<p> $$S_{mm} = 2\sum_{j=1}^{n}x_j^2$$</p>


<p> $S_{mb} = \dfrac{\partial^2 S}{\partial b \partial m} 2 [m\sum_{j=1}^{n}x_j^2 - \sum_{j=1}^{n}x_jy_j+b\sum_{j=1}^{n}x_j]$</p>
<p> $\dfrac{\partial^2 S}{\partial b \partial m}m\sum_{j=1}^{n}x_j^2=0$ & $\dfrac{\partial^2 f}{\partial b \partial m}$ </p>
<p> $\dfrac{\partial^2 s}{\partial b \partial m}b\sum_{j=1}^{n}x_j = \sum_{j=1}^{n}x_j$</p>
<p> $$S_{mb} = 2\sum_{j=1}^{n}x_j$$ <p>

<p> $S_{bb}=  \dfrac{\partial^2 S}{\partial^2 b} 2[m\sum_{j=1}^{n}x_j - \sum_{j=1}^{n}y_j + \sum_{j=1}^{n}b]$</p>
<p> $\dfrac{\partial^2 S}{\partial^2 b} m\sum_{j=1}^{n}x_j=0$ & $\dfrac{\partial^2 f}{\partial^2 b}- \sum_{j=1}^{n}y_j =0$</p>
<p> $\dfrac{\partial^2 S}{\partial^2 b} \sum_{j=1}^{n}b = n$</p>
<p> $$S_{bb} = 2n$$</p>

<p> **Portanto temos que a Hessiana de S é:**</p>
$$H(m,b)= \left[\begin{array}{cc}
2\sum_{j=1}^{n}x_j^2 & 2\sum_{j=1}^{n}x_j\\
2\sum_{j=1}^{n}x_j & 2n\\
\end{array}
\right]_{2\times 2}$$


## (d) Teste da segunda derivada para sabermos se é ponto mínimo

<p> $D= detH(m,b)= S_{mm}(m,b)S_{bb} - S_{mb}(m,b)^2$</p>
<p> $detH(m,b)= 2\sum_{j=1}^{n}x_j^2 \times 2n - (2\sum_{j=1}^{n}x_j)^2$ </p>
<p> $detH(m,b)= 4n\sum_{j=1}^{n}x_j^2- 4(\sum_{j=1}^{n}x_j)^2$</p>
<p> Assumindo que $2\sum_{j=1}^{n}x_j^2 - (2\sum_{j=1}^{n}x_j)^2 > 0$. Então:</p>
<p> $detH(m,b)>0$.Como: $S_{mm} = 2\sum_{j=1}^{n}x_j^2 >0$, **então o ponto (m,b) é ponto de mínimo local**</p>


